[versions]
spring-boot = "4.0.0-RC2"
webjars-livereload = "4.0.2"

[libraries]
servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-webmvc = { module = "org.springframework:spring-webmvc" }
webjars-livereload = { module = "org.webjars.npm:livereload-js", version.ref = "webjars-livereload" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
